version: 2
jobs:
  first:
    docker: 
     - image: circleci/node:4.8.2
    steps:
      - checkout
      - run: echo "A first hello"
  second:
    docker: 
     - image: circleci/node:4.8.2
    steps:
      - checkout
      - run: echo "A second hello"

workflows:
  version: 2
  first_and_second:
    jobs:
      - one
      - two 