version: 2.1
jobs:
  one:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - run: echo " A first hello"
  two:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - run: echo "a more familiar hello"

workflows:
  version: 2
  one_and_two:
    jobs:
      - one
      - two