version: 2
jobs:
  build:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - run: npm install
      - save_cache:
          Key: npm-cache-{{ .Brach }}-{{ checksum "package.json" }}
          paths:
            -node_modules